local script_dir = arg[0]:match('(.*/)') or './'
package.path = script_dir .. '../../../../src/engine/?.lua;' .. script_dir .. '?.lua;' .. package.path

local h = require('helpers')
local engine = require('engine')

h.test('engine.new() takes no args and returns an instance with no stdout wired', function()
	local e = engine.new()
	h.assert_true(e ~= nil, 'engine instance created')
	h.assert_true(e.stdout_obj == nil, 'no stdout wired at construction')
end)

h.test('engine:stdout({stdout = X}) attaches the given stdout', function()
	local stdout = h.FakeStdout.new()
	local e = engine.new()
	e:stdout({stdout = stdout})
	h.assert_true(e.stdout_obj == stdout, 'stdout wired to the object we passed')
end)

h.test('engine:hi() writes "hi" to the wired stdout', function()
	local stdout = h.FakeStdout.new()
	local e = engine.new()
	e:stdout({stdout = stdout})
	e:hi()
	h.assert_eq(stdout:get_all(), 'hi\n', 'stdout received "hi\\n"')
end)

h.test('engine:hi() raises if no stdout has been wired', function()
	local e = engine.new()
	h.assert_raises(function()
		e:hi()
	end, 'no stdout is wired')
end)

h.test('engine:load(source) accepts a Caspian source string', function()
	local stdout = h.FakeStdout.new()
	local e = engine.new()
	e:stdout({stdout = stdout})
	e:load('$x = 1 + 2')
	h.assert_eq(e.source, '$x = 1 + 2', 'source stashed on engine')
	h.assert_eq(stdout:get_all(), '', 'load() writes nothing to stdout yet')
end)

h.test('engine:load(source) works without any stdout wired', function()
	local e = engine.new()
	e:load('$x = 1 + 2')
	h.assert_eq(e.source, '$x = 1 + 2', 'source stashed without stdout being required')
end)

h.test('two engines with different stdouts stay independent', function()
	local s1 = h.FakeStdout.new()
	local s2 = h.FakeStdout.new()
	local e1 = engine.new()
	local e2 = engine.new()
	e1:stdout({stdout = s1})
	e2:stdout({stdout = s2})
	e1:hi()
	e1:hi()
	e2:hi()
	h.assert_eq(s1:get_all(), 'hi\nhi\n', 'e1 wrote to s1 only')
	h.assert_eq(s2:get_all(), 'hi\n', 'e2 wrote to s2 only')
end)

h.test('engine:stdout({stdout = X}) can rewire mid-run', function()
	local s1 = h.FakeStdout.new()
	local s2 = h.FakeStdout.new()
	local e = engine.new()
	e:stdout({stdout = s1})
	e:hi()
	e:stdout({stdout = s2})
	e:hi()
	h.assert_eq(s1:get_all(), 'hi\n', 'first hi went to s1')
	h.assert_eq(s2:get_all(), 'hi\n', 'second hi went to s2')
end)
