--[[
{
	"module": "engine",
	"role": "Top-level runtime that drives a CVM. One engine per open DB connection. Owns the SQLite handle, tracks the current process, dispatches frames on that process's stack, and shuts down when nothing is left to run. Sits above `object` and `frame` — the engine constructs them and calls their methods rather than being one itself.",
	"exports": {
		"new":          "(db) -> engine — constructor; binds an lsqlite3 handle",
		"object_by_pk": "(pk) -> object — canonical pk-to-object load; nil if no row",
		"add_bucket":   "(for_object_pk) -> new bucket's object_pk — INSERTs a HashPrimitive owned by the target's owner_role"
	},
	"policy": "Engine DB access goes through dedicated per-statement methods only — no ad-hoc db:exec / db:nrows / db:prepare. Each cached SQL is its own method on the engine class; each method lazily preps and caches its prepared statement on the instance.",
	"performance": "Every method on this class runs on hot paths — most fire on every statement dispatch — and any cycle saved multiplies across the whole running program.",
	"status": "sketch — walking-skeleton, first pass at Lua-native class file"
}
]]

--[[
# Engine

The top-level runtime that drives a CVM. One engine per open DB
connection. Owns the SQLite handle, tracks the current process,
dispatches frames on that process's stack, and shuts down when nothing
is left to run. Sits above `object` and `frame` — constructs them and
calls their methods rather than being one of them.

**Policy: DB access via cached-statement methods only.** No ad-hoc
`db:exec`, no inline `db:nrows`, no `db:prepare` scattered through
engine code. Each SQL the engine needs is its own method on the engine
class, and each of those methods lazily caches its prepared statement
on the instance. The rule buys reuse (every SQL prepared once per
instance), one source of truth per statement (each SQL lives in
exactly the method that returns its prepared handle), and testable-
in-isolation methods (each can be called on a fresh engine against a
test DB with no cross-statement setup).

**Every method on this page must be as efficient as possible** — these
are hot paths, most run on every statement dispatch, and any cycle
saved multiplies out across the whole running program.
]]

local object = require("object")

local engine = {}
engine.__index = engine

--[[
## Constructing an engine

`engine.new(db)` takes an already-open lsqlite3 handle — with
`foreign_keys` and `recursive_triggers` pragmas already enabled per the
CVM's per-connection rules — and wraps it as an engine instance. Each
cached-statement method (`object_by_pk`, `add_bucket`, ...) lazily
populates its own `self.stmt_<name>` field on first use, so there's
nothing to preallocate here.
]]
function engine.new(db)
	local self = setmetatable({}, engine)
	self.db = db
	return self
end

--[[
## `object_by_pk` — canonical pk-to-object load

Takes a primary key and returns the corresponding objects row wrapped
as an object. `nil` if no row exists for that pk.

Caller-side:

    local obj = engine:object_by_pk(pk)

The lazy-prepare + bind + iterate + reset dance lives inside the
method. `stmt:reset()` runs on every call — required by lsqlite3 for
reusable prepared statements, without it the next `bind_values` on the
same handle raises.

**Cache field: `self.stmt_object_by_pk`.** First call preps and stores;
subsequent calls skip that block and go straight to bind. The `stmt_`
prefix keeps the field name from colliding with the method itself.

`object.new(self, row)` wraps the row as an object instance —
dispatch to the right class (HashPrimitive, ArrayPrimitive, scalar)
and any per-pk caching live inside `object.new` itself.
]]
function engine:object_by_pk(pk)
	if not self.stmt_object_by_pk then
		self.stmt_object_by_pk = self.db:prepare(
			"select * from objects where object_pk = ?"
		)
	end

	local stmt = self.stmt_object_by_pk
	stmt:bind_values(pk)
	local row

	for r in stmt:nrows() do
		row = r
	end

	stmt:reset()

	if not row then
		return nil
	end

	return object.new(self, row)
end

--[[
## `add_bucket` — INSERT a bucket, return its pk

INSERTs a HashPrimitive as the bucket for a given owner and returns
the new bucket's `object_pk`. Used by `object:bucket` as the lazy-
create branch of the object's `bucket` accessor.

**Derives `owner_role` from the target.** The `insert ... select`
reads the `owner_role` off the target row and uses it for the new
bucket. Callers don't pass an owner_role; the bucket naturally
inherits the ownership of the object it's a bucket for.

**Uses SQLite `RETURNING`** to hand the new bucket's `object_pk` back
in the same round trip. The pk is generated by the default expression
on `objects.object_pk` (a UUID via `randomblob`); RETURNING captures
it as it lands.

**Also fires the `objects_denormalize_bucket` trigger** inside the
same statement. The trigger updates the target row's `bucket_pk`
column to the new bucket's `object_pk` — the value RETURNING gives
back equals what the target's `bucket_pk` becomes. Callers don't have
to re-read the target row to learn its new `bucket_pk`.

**Cache field: `self.stmt_add_bucket`.** Same lazy-prepare pattern as
`object_by_pk` — one INSERT with SELECT + RETURNING gets parsed once
per engine instance and reused across every bucket creation
thereafter.
]]
function engine:add_bucket(for_object_pk)
	if not self.stmt_add_bucket then
		self.stmt_add_bucket = self.db:prepare(
			"insert into objects (primitive, bucket_for, owner_role) " ..
			"select 'h', ?1, owner_role from objects where object_pk = ?1 " ..
			"returning object_pk"
		)
	end

	local stmt = self.stmt_add_bucket
	stmt:bind_values(for_object_pk)
	local bucket_pk

	for r in stmt:nrows() do
		bucket_pk = r.object_pk
	end

	stmt:reset()
	return bucket_pk
end

return engine
