local script_dir = arg[0]:match('(.*/)') or './'
package.path = script_dir .. '../../../code/lua/?.lua;' .. script_dir .. '?.lua;' .. package.path

local trivet = require('trivet')
local h = require('helpers')

h.test('create_child appends and links parent', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	h.assert_eq(a.parent, r)
	h.assert_eq(r.first_child, a)
end)

h.test('insert_child at position 1', function()
	local r = trivet.new('r')
	r:create_child('b')
	r:create_child('c')
	local a = r:insert_child(1, 'a')
	h.assert_seq(h.values_of(r:children()), {'a', 'b', 'c'})
	h.assert_eq(a.parent, r)
end)

h.test('insert_child in the middle', function()
	local r = trivet.new('r')
	r:create_child('a')
	r:create_child('c')
	r:insert_child(2, 'b')
	h.assert_seq(h.values_of(r:children()), {'a', 'b', 'c'})
end)

h.test('insert_child at end (n+1)', function()
	local r = trivet.new('r')
	r:create_child('a')
	r:insert_child(2, 'b')
	h.assert_seq(h.values_of(r:children()), {'a', 'b'})
end)

h.test('insert_child raises on out-of-range index', function()
	local r = trivet.new('r')
	r:create_child('a')
	h.assert_raises(function()
		r:insert_child(0, 'x')
	end, 'out of range')
	h.assert_raises(function()
		r:insert_child(99, 'x')
	end, 'out of range')
	h.assert_raises(function()
		r:insert_child(-1, 'x')
	end, 'out of range')
end)

h.test('insert_child raises on non-integer index', function()
	local r = trivet.new('r')
	h.assert_raises(function()
		r:insert_child(1.5, 'x')
	end)
	h.assert_raises(function()
		r:insert_child('one', 'x')
	end)
end)

h.test('remove detaches child and returns the detached node', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	local detached = a:remove()
	h.assert_eq(detached, a, 'returns the detached node itself')
	h.assert_seq(h.values_of(r:children()), {'b'})
	h.assert_nil(a.parent)
	h.assert_true(a.is_root, 'a is now a root')
	-- b unaffected
	h.assert_eq(b.parent, r)
end)

h.test('remove on an already-root node is a no-op', function()
	local a = trivet.new('a')
	local detached = a:remove()
	h.assert_eq(detached, a)
	h.assert_true(a.is_root)
	h.assert_nil(a.parent)
end)

h.test('remove takes the subtree with it (structure preserved)', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local a1 = a:create_child('a1')
	local a2 = a1:create_child('a2')
	a:remove()
	-- Subtree structure still intact
	h.assert_eq(a1.parent, a)
	h.assert_eq(a2.parent, a1)
	h.assert_eq(a.child_count, 1)
	-- Old parent no longer holds them
	h.assert_eq(r.child_count, 0)
	-- And the detached root can be moved back
	a:move_to(r)
	h.assert_eq(a.parent, r, 'a came back under r')
	h.assert_eq(a2.parent, a1, 'subtree still intact')
end)

h.test('move_to reparents within tree', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	local x = a:create_child('x')
	x:move_to(b)
	h.assert_eq(x.parent, b)
	h.assert_seq(h.values_of(a:children()), {})
	h.assert_seq(h.values_of(b:children()), {'x'})
end)

h.test('move_to preserves subtree', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	local x = a:create_child('x')
	local x1 = x:create_child('x1')
	x:move_to(b)
	h.assert_eq(x1.parent, x)
	h.assert_eq(x.parent, b)
	h.assert_seq(h.values_of(x:descendants()), {'x1'})
end)

h.test('move_to a detached node re-attaches subtree', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	local x = a:create_child('x')
	x:remove()
	h.assert_nil(x.parent)
	x:move_to(b)
	h.assert_eq(x.parent, b)
	h.assert_seq(h.values_of(b:children()), {'x'})
end)

h.test('move_to a root demotes it to child', function()
	local a = trivet.new('a')
	local b = trivet.new('b')
	b:move_to(a)
	h.assert_eq(b.parent, a)
	h.assert_false(b.is_root)
	h.assert_true(a.is_root)
end)

h.test('move_to refuses cycle (parent = self)', function()
	local r = trivet.new('r')
	h.assert_raises(function()
		r:move_to(r)
	end, 'cycle')
end)

h.test('move_to refuses cycle (parent = descendant)', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local a1 = a:create_child('a1')
	h.assert_raises(function()
		r:move_to(a1)
	end, 'cycle')
	h.assert_raises(function()
		a:move_to(a1)
	end, 'cycle')
end)

h.test('move_to across unrelated trees transfers the subtree', function()
	local r1 = trivet.new('r1')
	local a = r1:create_child('a')
	local b = a:create_child('b')
	local r2 = trivet.new('r2')
	a:move_to(r2)
	h.assert_eq(a.parent, r2, 'a is under r2')
	h.assert_eq(b.parent, a, 'subtree still intact')
	h.assert_eq(r1.child_count, 0, 'r1 no longer holds a')
	h.assert_eq(r2.child_count, 1, 'r2 holds a')
end)

h.test('move_to a root into another root demotes it', function()
	local r1 = trivet.new('r1')
	local r2 = trivet.new('r2')
	r1:move_to(r2)
	h.assert_eq(r1.is_root, false, 'no longer a root')
	h.assert_eq(r1.parent, r2, 'parented under r2')
end)

h.test('move_before reorders siblings', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	local c = r:create_child('c')
	c:move_before(a)
	h.assert_seq(h.values_of(r:children()), {'c', 'a', 'b'})
	local _ = b
end)

h.test('move_after reorders siblings', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	local c = r:create_child('c')
	a:move_after(c)
	h.assert_seq(h.values_of(r:children()), {'b', 'c', 'a'})
end)

h.test('move_before with self is a no-op', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	a:move_before(a)
	h.assert_seq(h.values_of(r:children()), {'a', 'b'})
	local _ = b
end)

h.test('move_before raises when nodes do not share parent', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	local x = a:create_child('x')
	h.assert_raises(function()
		x:move_before(b)
	end, 'do not share a parent')
end)

h.test('move_before raises when nodes are in unrelated trees', function()
	local a = trivet.new('a')
	local b = trivet.new('b')
	local x = a:create_child('x')
	h.assert_raises(function()
		x:move_before(b)
	end, 'do not share a parent')
end)

h.test('move_to preserves sibling order at destination (appends)', function()
	local r = trivet.new('r')
	local a = r:create_child('a')
	local b = r:create_child('b')
	local c = r:create_child('c')
	local x = a:create_child('x')
	x:move_to(b)
	b:create_child('y')
	h.assert_seq(h.values_of(b:children()), {'x', 'y'})
	local _ = c
end)
