--[[
{
  "file": "orlando/tests/content_type/test_content_type.lua",
  "role": "Unit tests for orlando.content_type — lookup table + filename parsing."
}
]]
local runner  = require("support.runner")
local assert_ = require("support.assert")
local ct      = require("orlando.content_type")

runner.suite("content_type")

runner.test("by extension: html", function()
    assert_.equal(ct.for_ext("html"), "text/html; charset=utf-8")
end)
runner.test("by extension: svg", function()
    assert_.equal(ct.for_ext("svg"), "image/svg+xml")
end)
runner.test("by extension: json", function()
    assert_.equal(ct.for_ext("json"), "application/json")
end)
runner.test("by extension: png", function()
    assert_.equal(ct.for_ext("png"), "image/png")
end)
runner.test("by extension: md", function()
    assert_.equal(ct.for_ext("md"), "text/markdown; charset=utf-8")
end)
runner.test("by extension: markdown", function()
    assert_.equal(ct.for_ext("markdown"), "text/markdown; charset=utf-8")
end)
runner.test("by extension: css", function()
    assert_.equal(ct.for_ext("css"), "text/css; charset=utf-8")
end)
runner.test("by extension: js", function()
    assert_.equal(ct.for_ext("js"), "text/javascript; charset=utf-8")
end)
runner.test("by extension: jpg and jpeg both map to image/jpeg", function()
    assert_.equal(ct.for_ext("jpg"),  "image/jpeg")
    assert_.equal(ct.for_ext("jpeg"), "image/jpeg")
end)
runner.test("by extension: gif", function()
    assert_.equal(ct.for_ext("gif"), "image/gif")
end)
runner.test("by extension: webp", function()
    assert_.equal(ct.for_ext("webp"), "image/webp")
end)
runner.test("by extension: ico (favicon)", function()
    assert_.equal(ct.for_ext("ico"), "image/x-icon")
end)
runner.test("by extension: txt is text/plain", function()
    assert_.equal(ct.for_ext("txt"), "text/plain; charset=utf-8")
end)
runner.test("by extension: code/config types map to text/plain", function()
    local plain = "text/plain; charset=utf-8"
    assert_.equal(ct.for_ext("sh"),      plain)
    assert_.equal(ct.for_ext("lua"),     plain)
    assert_.equal(ct.for_ext("caspian"), plain)
    assert_.equal(ct.for_ext("sql"),     plain)
    assert_.equal(ct.for_ext("toml"),    plain)
    assert_.equal(ct.for_ext("conf"),    plain)
end)
runner.test("by extension: case-insensitive", function()
    assert_.equal(ct.for_ext("HTML"), "text/html; charset=utf-8")
    assert_.equal(ct.for_ext("Svg"),  "image/svg+xml")
end)
runner.test("by extension: unknown returns DEFAULT", function()
    assert_.equal(ct.for_ext("xyz"), ct.DEFAULT)
end)
runner.test("by extension: nil returns DEFAULT", function()
    assert_.equal(ct.for_ext(nil), ct.DEFAULT)
end)

runner.test("by filename: page.md", function()
    assert_.equal(ct.for_file("page.md"), "text/markdown; charset=utf-8")
end)
runner.test("by filename: nested path graphics/logo.svg", function()
    assert_.equal(ct.for_file("graphics/logo.svg"), "image/svg+xml")
end)
runner.test("by filename: dotted basename foo.bar.json", function()
    assert_.equal(ct.for_file("foo.bar.json"), "application/json")
end)
runner.test("by filename: no extension returns DEFAULT", function()
    assert_.equal(ct.for_file("README"), ct.DEFAULT)
end)
runner.test("by filename: directory-looking path foo.html/bar returns DEFAULT", function()
    -- 'bar' has no dot, so falls through to DEFAULT — confirms the extension
    -- regex is anchored at the end and skips slashes
    assert_.equal(ct.for_file("foo.html/bar"), ct.DEFAULT)
end)
runner.test("by filename: nil returns DEFAULT", function()
    assert_.equal(ct.for_file(nil), ct.DEFAULT)
end)
